# Site settings
title: My Technical Blog
email: zetsu@domain.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/blog-technical"
url: "http://colinbut.github.io"

author:
  name     : 'Colin But'
  email    : colin.but@hotmail.co.uk 
  url      : http://colinbut.github.io
  facebook : http://facebook.com/colin.but
  twitter  : http://twitter.com/colin_but

github: https://github.com/colinbut/blog-technical
disqus_shortname: "colinbut"
google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
